name: CI/CD for Streamlit App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Google Cloud SDK
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: invertible-pipe-446908-p9

    # Build and push Docker image to Google Container Registry
    - name: Build and push Docker image
      run: |
        docker build -t gcr.io/invertible-pipe-446908-p9/streamlit-ocr .
        docker push gcr.io/invertible-pipe-446908-p9/streamlit-ocr

    # Deploy to Google Cloud Run
    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy streamlit-ocr \
          --image gcr.io/invertible-pipe-446908-p9/streamlit-ocr \
          --platform managed \
          --region asia-south1 \
          --allow-unauthenticated
